### ISSUE TITLE
No M1 support because GoogleMaps pod < 6.0.1

### ISSUE THREAD

**Issue by karatekid430** [react-native-maps/react-native-maps#4097]
# Bug report

## Summary

ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/nicholas/git/tenant/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64

This happens when building on an M1 Apple machine without Rosetta

## Environment info

    "react-native": "0.66.3",
    "react": "17.0.2",
    "react-native-maps": "^0.30.1",

`react-native info` output: // The command is actually npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 83.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 25, 27, 28, 30, 31, 32
      Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_322 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps to reproduce

1. Build app on M1 Mac without Rosetta with react-native-maps installed (it uses an old 5.1.0 GoogleMaps pod which uses the old framework) - see https://cloud.google.com/blog/products/maps-platform/announcing-version-60-maps-and-places-sdks-ios
2. You will see the error
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/nicholas/git/tenant/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64

Describe what you expected to happen:

It should build and run the react-native app under arm64 without Rosetta

Describe what you actually happens:

ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/nicholas/git/tenant/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64

See Google's URL with this same error, solution is to use GoogleMaps pod v6 instead of v5.
https://cloud.google.com/blog/products/maps-platform/announcing-version-60-maps-and-places-sdks-ios

## Reproducible sample code

Create new react-native app on M1, add react-native-maps, pod install, note how GoogleMaps is 5.1.0 instead of 6.x. Build in Xcode without Rosetta, note how the error is shown.

Please bump the version of the pod dependency. :)

**Comment by SakeFabi** [comment]
Same here not working on M1 chip.

**Comment by Simon-TechForm** [comment]
This is alredy merged. There's no release for it yet though :) See #4061. You could try installing from the master branch.

**Comment by isipisi281** [comment]
Working fine 4 me mmhmmmm

**Comment by SakeFabi** [comment]
@Simon-TechForm will take a look thanks!

**Comment by karatekid430** [comment]
> I am having the same issue. I am using M1 pro and after installing react-native-maps, I did pod install, and after the project is not building. In error warning, it clearly says that it's expecting x86 architecture but it's linking with arm64. I believe this lib is still not updated for the M1
> 
> These are the errors that I am getting.
> 
> <img alt="Screenshot 2022-02-16 at 9 29 06 PM" width="946" src="https://user-images.githubusercontent.com/30371302/154351688-2209f1e3-0b6b-41d1-9b62-4c96b4727d14.png">
> 
> <img alt="Screenshot 2022-02-16 at 9 28 25 PM" width="946" src="https://user-images.githubusercontent.com/30371302/154351701-a9d3de7d-ceb3-490b-a453-942786f37cfe.png">

That is a different issue, make sure you are excluding arm64 for any ios simulator SDK both in your Podfile for your pods and in Xcode for your main targets. Do not exclude for any SDK. That will ruin it.

**Comment by mokshmodi96** [comment]
> > I am having the same issue. I am using M1 pro and after installing react-native-maps, I did pod install, and after the project is not building. In error warning, it clearly says that it's expecting x86 architecture but it's linking with arm64. I believe this lib is still not updated for the M1
> > These are the errors that I am getting.
> > <img alt="Screenshot 2022-02-16 at 9 29 06 PM" width="946" src="https://user-images.githubusercontent.com/30371302/154351688-2209f1e3-0b6b-41d1-9b62-4c96b4727d14.png">
> > <img alt="Screenshot 2022-02-16 at 9 28 25 PM" width="946" src="https://user-images.githubusercontent.com/30371302/154351701-a9d3de7d-ceb3-490b-a453-942786f37cfe.png">
> 
> That is a different issue, make sure you are excluding arm64 for any ios simulator SDK both in your Podfile for your pods and in Xcode for your main targets. Do not exclude for any SDK. That will ruin it.

Your solution worked for me as my app project was excluding the arm64 but not the pods project updating it solved the issue

**Comment by karatekid430** [comment]
Does anybody know when the next release is scheduled? Cheers :)

**Comment by Simon-TechForm** [comment]
@karatekid430 can't give you an exact date, but I'm looking to push a new release relatively soon. 

I'm going to close this in favour of #3527 to try and keep the discussion in one place :)

**Comment by saeedtkh** [comment]
any news? I have the same issue!

**Comment by russmenum** [comment]
Can I ask, what did everyone do to get ```pod install``` using google maps to even run right on an M1 Mac?

If I ```cd ios``` and ```pod install``` with 

```
# React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```

it will not even finish the pod install

**Comment by Darapsas** [comment]
For the unfortunate few that might end up here. I advise you to read this [article](https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9), for the lazy ones you should update your podfile postinstall script to this one:
```podfile
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
     # Add these three lines down below -----------------------------------------------
     installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
     # --------------------------------------------------------------------------------
  end
```

Some background, I was upgrading my project to the latest `react-native` version on the new M1 MacBook, recreated ios directory with `npx react-native init ...` and encountered with this issues while configuring `react-native-maps`, this issue is still valid one these package versions and is resolved with the above solution:
```json
...
    "react": "18.0.0",
    "react-native": "0.69.0",
    "react-native-maps": "0.31.1",
...
```

**Comment by russmenum** [comment]
>``` post_install do |installer|
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>     
>      # Add these three lines down below -----------------------------------------------
>      installer.pods_project.build_configurations.each do |config|
>        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>      end
>      # --------------------------------------------------------------------------------
>   end```

I added this post-install but still get errors even trying to do ```pod install``` what is the magic trick to complete ```pod install``` on an M1 so you can build apps using MAPS on an M1?

**Comment by russmenum** [comment]
Oh I have cleaned and the like 1000 times

If Google maps is in the podfile it wont do ```pod install``` on the M1, runs fine on Intel Mac

```
Auto-linking React Native modules for target `frdrivertrackapp`: RNBackgroundFetch, RNBackgroundGeolocation, RNGestureHandler, RNPermissions, RNReanimated, RNScreens, ReactNativeGetLocation, TextToSpeech, react-native-background-actions, react-native-config, react-native-keep-awake, react-native-maps, and react-native-notifications
Analyzing dependencies
objc[39498]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1df56eb90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1042bc2c8). One of the two will be used. Which one is undefined.
objc[39498]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1df56ebe0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1042bc318). One of the two will be used. Which one is undefined.

```

and the error shows

```
### Error

```

```
LoadError - dlsym(0x209519740, Init_ffi_c): symbol not found - /Users/[MACUSER]/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/[MACUSER]/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
```

If you remove 
```
# React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```
from the podfile everything runs fine on the M1, but defeats the point.

My understanding is this has something to do with Google Pods and M1 not being x86, but clearly people have this runing on M1 macs, so trying to figuer out how?

**Comment by russmenum** [comment]
> arch -x86_64 pod install

Thank you both of you, I had been googling how to fix this for a bit. for whatever reason it never linked me to the doc @Darapsas referenced.

Because there are so many threads on this I would almost say it might be appropriate to add that post to the readme, or at least the commands.

**Comment by SakeFabi** [comment]
There seems to be something I am not getting. - I used arch -x86_64 pod install all the time but when I add the package in the podfile it will throw me an error:
`/Users/Me/.../ios/myProject.xcodeproj The linked library 'libPods-myProject.dev.a' is missing one or more architectures required by this target: x86_64.`
Which in some way makes sense. I am excluding it and it seems google maps package expects it? 
Now you guys seem to get it running, can anybody help?

**Comment by SakeFabi** [comment]
@russmenum did you already find a solution? Whenever I add the line in the podfile the build will fail regardless of whether I follow the other steps or not..

**Comment by russmenum** [comment]
> @russmenum did you already find a solution? Whenever I add the line in the podfile the build will fail regardless of whether I follow the other steps or not..

The ```arch -x86_64``` worked for me, but I am not excluding architectures on the M1, so is there a reason you need to exclud?

**Comment by NgocLe1001** [comment]
[this](https://github.com/react-native-maps/react-native-maps/issues/4097#issuecomment-1170370876) helps me. Thank you
