### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by parmarravi** [react-native-maps/react-native-maps#4258]
### Summary

ERROR 

> fatal error: module map file '/Users/raviparmar/Library/Developer/Xcode/DerivedData/appname-fzfidluhroyaqbftlvcalahizjbe/Build/Products/Release-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.modulemap' not found
> 1 error generated.

```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@react-native-community/datetimepicker": "^6.1.2",
    "@react-native-firebase/app": "^14.9.1",
    "@react-native-firebase/crashlytics": "^14.9.1",
    "@react-native-firebase/messaging": "^14.9.1",
    "@react-native-picker/picker": "^2.4.1",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "add": "^2.0.6",
    "axios": "^0.27.2",
    "dayjs": "^1.10.6",
    "decode-google-map-polyline": "^1.0.1",
    "install": "^0.13.0",
    "js-base64": "^3.7.2",
    "metro-react-native-babel-transformer": "^0.70.2",
    "react": "^18.0.0",
    "react-native": "^0.68.1",
    "react-native-calendars": "^1.1283.0",
    "react-native-confirmation-code-field": "^7.2.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "2.4.1",
    "react-native-maps": "^0.31.1",
    "react-native-maps-animated-polyline": "^1.0.6",
    "react-native-marquee": "^0.3.2",
    "react-native-material-menu": "^2.0.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-dropdown": "^1.0.2",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-paper": "^4.12.1",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-reanimated": "2.8.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-shimmer": "^0.6.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.3.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-vector-icons": "^9.1.0",
    "react-native-webview": "^11.18.2",
    "validate.js": "^0.13.1",
    "yarn": "^1.22.17"
  },
```

iOS POD file

```
# $FirebaseSDKVersion = '8.10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

install! 'cocoapods', :deterministic_uuids => false

target 'appname' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # react-native-maps dependencies
   rn_maps_path = '../node_modules/react-native-maps' # This path is likely to be `../node_modules/react-native-maps` in your own project.
#
#  pod 'react-native-maps', path: rn_maps_path
#  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils', '~> 4.1.0'
  
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path

  #  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  #  rn_maps_path = '../node_modules/react-native-maps'
  #  pod 'react-native-google-maps', :path => rn_maps_path

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'


  target 'appnameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

How to fix the build issue?

### Reproducible sample code

```TSX
"
```

### Steps to reproduce

use the same dependency and run it from Mac book pro m1 chip

### Expected result

Run without error

### Actual result

Run without error

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.68.1

### Are you using Expo?

No

### Device(s)

iPhone 13 pro

**Comment by parmarravi** [comment]
Issue resolved by opening xcworkspace file in Xcode and recompiling all the pod files.

**Comment by ariesxje** [comment]
Hi, I have exact same issue. How did you compile the pod files?

**Comment by OXcarXierra** [comment]
I have the same issue too. anybody with solutions?

**Comment by MoeMamdouh** [comment]
same issue here with build release or archive

**Comment by OXcarXierra** [comment]
I still dont know the reason but this just solved after restarting my mac few days later

**Comment by evangrim** [comment]
Compile all pod files:
cd myproject/ios && pod install --repo-update

If you want to be really sure the pods are updated, you can also `cd ios && rm -rf Pods && pod install` (note there's a Podfile.lock -- possible to remove this and install again; lockfile will be generated and pods will be installed based on node_modules and/or podfile, depending on your RN version and podfile setup).

**Comment by karpinski1994** [comment]
doesn't work for me : /

**Comment by janoist1** [comment]
it's 2023 and the issue is still alive

**Comment by marcozciuffini** [comment]
I managed to remove this issue, by ensuring that the Pods project had excluded architecture 'arm64' for 'Any iOS simulator SDK', my podfile had only set this for the app target

**Comment by SafiDS** [comment]
<img width="1075" alt="Screenshot 2023-10-25 at 11 04 04 PM" src="https://github.com/react-native-maps/react-native-maps/assets/25033681/90a375ad-5f6f-48da-a3c8-26a1d1b46c53">

Make sure it should be on Projects and Pods level otherwise it will not work

Its works for me

**Comment by harshit251102** [comment]
<img width="1448" alt="Image" src="https://github.com/user-attachments/assets/4424420f-b561-4daf-80ae-1c4fb8b0a782" />
I added arm64 in my excluded architecture, then also facing the issue

inside podfile - 
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

postinstall script -
post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

**Comment by harshit251102** [comment]
Adding this in podfile, resolved it for me - 
`
    # Exclude arm64 architecture for iOS Simulator
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
`
