### ISSUE TITLE
Marker onPress not triggered - touchable area is different than marker itself

### ISSUE THREAD

**Issue by mishkeTz** [react-native-maps/react-native-maps#4472]
### Summary

https://user-images.githubusercontent.com/15350199/193890085-8c9140f4-6135-4bda-a173-fc584dc46c23.mov

### Reproducible sample code

```TSX
const Markers = useMemo(() => markers?.map(marker => {
  const { coordinate: { latitude, longitude } } = marker;
  return (
    <Marker
      key={`marker-${latitude}-${longitude}`}
      tracksViewChanges={false}
      coordinate={marker.coordinate}
      onPress={() => onMarkerPress(marker)}
    >
      <View style={styles.markerTextWrapper} >
        <Text style={styles.markerText}>{marker.count}</Text>
      </View>
    </Marker>
  );
}), [markers]);

<MapView
  ref={mapRef}
  mapType='hybrid'
  initialRegion={region}
  style={styles.mapView}
  loadingEnabled
  showsBuildings={false}
  showsMyLocationButton={false}
  showsPointsOfInterest={false}
  showsCompass={false}
  showsScale={false}
  showsIndoors={false}
>
  {Markers}
</MapView>
```

### Steps to reproduce

- Build on Android using google maps provider

### Expected result

Marker is clickable whenever I click on the rendered marker.

### Actual result

The marker touchable area is somewhere around (above) the actual marker. The marker is sometimes not clickable or only part of it is.

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.63.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Android

**Comment by wordisthebird** [comment]
I'm far from an expert but heres my code that works:
Ive shared a link of an article with the repo link where I got solution to work!

```
        <ClusteredMapView
        provider={PROVIDER_GOOGLE}
        clusterColor="red"
        ref={map}
        customMapStyle={MAP_LIGHT_STYLE}
        style={styles.mapView}
        initialRegion={region}
        onRegionChangeComplete={onRegionChangeComplete}>
        {markers.map((marker, index) => (
          <Marker
            ref={markerRef}
            key={index}
            tracksInfoWindowChanges={false}
            tracksViewChanges={Platform.OS === 'android' ? false : true}

            coordinate={{
              latitude: marker.coordinate.latitude,
              longitude: marker.coordinate.longitude,
            }}
            onPress={(e) => onMarkerPress(index)}
          >
            <Animated.View style={[styles.markerWrap]}>
                <Image
                  fadeDuration={0}
                  resizeMode="contain"
                  onLoadEnd={doRedraw}
                  style={styles.markerLogo}
                  source={require("../../../image.png")}
                />
            </Animated.View>

          </Marker>
        ))}
      </ClusteredMapView>
```

on marker press:
 ```
 const onMarkerPress = (index) => {
    console.log("Marker : ", index)

    setVisible(true)
    LayoutAnimation.configureNext(LayoutAnimation.Presets.linear);
    setCurrent(index);
  };
```

most help came from here:

https://dev.to/upsilon_it/how-to-do-map-clustering-with-react-native-10ih

**Comment by Simon-TechForm** [comment]
Hi @mishkeTz 👋 

My guess is that this is caused by the new renderer on android.

The touchable area is the same as always, but the labels beneath your markers are intercepting the taps/clicks (both the markers you are pressing are above city labels). Check out [my comment](https://github.com/react-native-maps/react-native-maps/pull/4055#issuecomment-1063358886) regarding changed behaviour on the new renderer.

You are able to trigger the markers onclick "around" it because of [this](https://github.com/react-native-maps/react-native-maps/issues/4386#issuecomment-1210491130).

If you aren't using the POI click listener, you should be able to "fix" this by not registrering the listener (e.g. commenting out): https://github.com/react-native-maps/react-native-maps/blob/c447dea5eb4551440b131e3003ac50e0c5709fa9/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L220

Could you try to patch that line and report back if that's the case for you as well?

**Comment by mishkeTz** [comment]
@Simon-TechForm 
That was the issue for me. Changing that fixed this weird behaviour.
I forgot to mention that I do use the new renderer.

I created a patch for this, if anyone finds himself in similar situation:

`diff --git a/node_modules/react-native-maps/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java b/node_modules/react-native-maps/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
index 38755bb..c05a08b 100644
--- a/node_modules/react-native-maps/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
+++ b/node_modules/react-native-maps/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
@@ -221,7 +221,7 @@ public class AirMapView extends MapView implements GoogleMap.InfoWindowAdapter,
     this.map = map;
     this.map.setInfoWindowAdapter(this);
     this.map.setOnMarkerDragListener(this);
-    this.map.setOnPoiClickListener(this);
+    // this.map.setOnPoiClickListener(this);
     this.map.setOnIndoorStateChangeListener(this);
 
     applyBridgedProps();`

**Comment by Nuno1123** [comment]
I'm having a similar issue. 
I have multiple markers and clusters.
I am not able to onPress any marker or cluster if over a POI. It always calls onPoiClick instead.
I am not willing to disable all onPoiClick as I want to be able to do so. Just when marker or cluster is over it. 

Any idea how to do so?

**Comment by GoktuqCan** [comment]
Hi, I've created a repository based on the solution I'm using in my current project. I hope you'd find it useful:
[https://github.com/GoktuqCan/react-native-maps-touchables](https://github.com/GoktuqCan/react-native-maps-touchables)

**Comment by maXXCZ1** [comment]
Hello, was this addressed in any recent stable release? I struggle to find more discussion about this topic, but at the same time i don't see any viable solution. I tracked mentioned `this.map.setOnPoiClickListener(this);` in my MapView.java but even this workaround did not work.
I am on 1.7.1 version and run into this issue once i started to use `enableLatestRenderer()`.

**Comment by findhumane** [comment]
I had this same issue (unable to click marker on top of a city name) and the patch for recent releases is slightly different as `AirMapView.java` has been renamed to `MapView.java`:

```diff
diff --git a/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapView.java b/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapView.java
--- a/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapView.java
+++ b/node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapView.java
@@ -242,7 +242,7 @@ public class MapView extends com.google.android.gms.maps.MapView implements Goog
 
     markerCollection.setInfoWindowAdapter(this);
     markerCollection.setOnMarkerDragListener(this);
-    this.map.setOnPoiClickListener(this);
+    //this.map.setOnPoiClickListener(this);
     this.map.setOnIndoorStateChangeListener(this);
 
     applyBridgedProps();
```

Solution after 1.20.0 is:

```
  <MapView poiClickEnabled={false}
```

**Comment by christophemenager** [comment]
Thank you @findhumane ! I confirm this fixed my issue

**Comment by MariuzM** [comment]
This also fixed the issue @findhumane.
I wonder how to make this perm change?

**Comment by CleverTomatoe** [comment]
Issue is still there. Custom marker has unreliable touchable area. Even without POI underneath

**Comment by Prazitstha** [comment]
> Hi, I've created a repository based on the solution I'm using in my current project. I hope you'd find it useful: https://github.com/GoktuqCan/react-native-maps-touchables

The issue is still there i have used you forked version of react native maps. Any updates how to solve it ?

**Comment by salah-ghanim** [comment]
@Prazitstha @MariuzM I just added support to disable PoI click disabling, this should improve click handling

https://github.com/react-native-maps/react-native-maps/pull/5210

as for having a specific clickable area around a marker, I don't think that's natively possible with googleMaps ... it should be doable with apple because native views are used on the map.

**Comment by rushant11** [comment]
@salah-ghanim @MariuzM @Prazitstha 

The red circle places are not pressable on the Android map. In iOS, it works fine. in Android, only those places are selectable, which places have default markers and which have green text colour. What’s the solution to this?

![Screenshot_1732184411](https://github.com/user-attachments/assets/594f07c4-bc0f-4197-a402-e27e42398b15)
