### ISSUE TITLE
Android map not working correctly, markers loading and not loading

### ISSUE THREAD

**Issue by edgarscr** [react-native-maps/react-native-maps#5236]
### Summary

map load but dont display markers.

### Reproducible sample code

```TSX
https://github.com/edgarscr/minimal-error-expo
```

### Steps to reproduce

npm -v 10.8.2

node -v v20.18.0

npm install

npx expo start --clear --go

### Expected result

Always need show markers 

### Actual result

open app markers appear on map on first load but if u close and open again map load but dont display markers.

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.76.3

### What version of Expo are you using?

SDK 52

### Device(s)

Any android

**Comment by JaRoMasterDev** [comment]
I am experiencing the same bug. I fetch the data for the region and the markers using a useEffekt hook, but sometimes the region and markers are just ignored and I see a world map without any data. The data is defintiely there, but not displayed. Even if I conditionally only render the map to get rendered once the data is loaded it might not show the region and markers.

**Comment by rgommezz** [comment]
> I am experiencing the same bug. I fetch the data for the region and the markers using a useEffekt hook, but sometimes the region and markers are just ignored and I see a world map without any data. The data is defintiely there, but not displayed. Even if I conditionally only render the map once the data is loaded it might not show the region and markers.

Experiencing the same. When that happens, neither `onMapReady`, nor `onMapLoaded` callback props fire. Scoped to RN 0.76, Expo v52, and the new Architecture

**Comment by Byte-Size-Coder** [comment]
Similar issue here, do we know if this is getting addressed?

**Comment by Shivemmer** [comment]
facing same issue

**Comment by stevekuznetsov** [comment]
Noticing the same issue with new architecture, on Android it seems like the child prop is not used to create actual child elements.

| working (iOS) | broken (android) |
| - | - |
| ![Screenshot from 2024-12-03 13-53-18](https://github.com/user-attachments/assets/340c4bec-d4a8-4b13-b236-48fbf109191f) | ![Screenshot from 2024-12-03 13-52-33](https://github.com/user-attachments/assets/7f666540-acb6-4157-91bb-aa567590047d) |

**Comment by FernandoAOborges** [comment]
same issue here. Any fix??

**Comment by stevekuznetsov** [comment]
@FernandoAOborges unless you have some novel information to add to the issue, please refrain from piling on to ask if something is fixed. Once progress is made, this issue will be updated. You may use the emoji reactions to the original report to indicate that you also face this issue.

**Comment by lucaspieran** [comment]
same problem here, any updates?

**Comment by Muneeb244** [comment]
Facing same issue with new architecture, any fixes?

**Comment by josmmv** [comment]
I'm faccing the same issue, had to set **newArchEnabled** to false in **gradle.properties** with `"react-native": "0.76.5"`

**Comment by AlessandroViol** [comment]
I'm facing this problem and I came up with a somewhat inelegant workaround. 
I've noticed that the MapView component doesn't actually invoke the onMapReady callback when the markers are not loaded. So, using a state variable and `useEffect`, I check if the markers are not loaded and force the re-render of the map if that's the case.
You can take a look at this code for some more insight, hopefully is not too ugly
```javascript
import { useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';

import MapView, { Marker } from 'react-native-maps';

export const NoteItem = ({ note }) => {
	const [mapReady, setMapReady] = useState(false);
	const [forceReload, setForceReload] = useState(0);

	useEffect(() => {
		const timer = setTimeout(() => {
			if (!mapReady) {
				console.warn('Map was not ready within 1 second. Forcing re-render.');
				setForceReload((prev) => prev + 1);
			}
		}, 1000);

		return () => clearTimeout(timer);
	}, [mapReady]);

	return (
		<View>
			<MapView
				key={forceReload} // Re-render map when this change
				style={styles.map}
				initialRegion={{
					latitude: note.location.coords.latitude,
					longitude: note.location.coords.longitude,
					latitudeDelta: 0.01,
					longitudeDelta: 0.01,
				}}
				onMapReady={() => {
					setMapReady(true);
					console.log('Map loaded');
				}}
			>
				<Marker
					coordinate={{ latitude: note.location.coords.latitude, longitude: note.location.coords.longitude }}
					title={note.title}
					description={note.note}
				></Marker>
			</MapView>
		</View>
	);
};


const styles = StyleSheet.create({
	map: {
		width: 300,
		height: 200,
	},
	modalView: {
		margin: 20,
		backgroundColor: 'white',
		borderRadius: 20,
		padding: 35,
		alignItems: 'center',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 4,
		elevation: 5,
	},
});
```

**Comment by ttebify** [comment]
If you are using Expo and run `npx expo install --check`, you will see in the logs that this package is not supported in React Native's New Architecture. I believe this will also affect bare React Native apps using the New Architecture.

<img width="781" alt="image" src="https://github.com/user-attachments/assets/7085af32-4e85-4bf8-830d-36151007e1a4" />

### Temp Solution

You do not have to downgrade Expo or React Native to fix this. Simply set `newArchEnabled` to `false` in your `app.json` and rebuild your app:

1. Update your `app.json`:
```json
{
  "expo": {
    "android": {
      "newArchEnabled": false
    }
  }
}
```

2. Rebuild your app by either:
   - Running `expo prebuild` again, or
   - Creating a new development build

This should resolve the marker issues you are experiencing.

**Comment by prechy123** [comment]
> I'm facing this problem and I came up with a somewhat inelegant workaround. I've noticed that the MapView component doesn't actually invoke the onMapReady callback when the markers are not loaded. So, using a state variable and `useEffect`, I check if the markers are not loaded and force the re-render of the map if that's the case. You can take a look at this code for some more insight, hopefully it's not too ugly
> 
> ```js
> import { useEffect, useState } from 'react';
> import { StyleSheet, View } from 'react-native';
> 
> import MapView, { Marker } from 'react-native-maps';
> 
> export const NoteItem = ({ note }) => {
> 	const [mapReady, setMapReady] = useState(false);
> 	const [forceReload, setForceReload] = useState(0);
> 
> 	useEffect(() => {
> 		const timer = setTimeout(() => {
> 			if (!mapReady) {
> 				console.warn('Map was not ready within 1 second. Forcing re-render.');
> 				setForceReload((prev) => prev + 1);
> 			}
> 		}, 1000);
> 
> 		return () => clearTimeout(timer);
> 	}, [mapReady]);
> 
> 	return (
> 		<View>
> 			<MapView
> 				key={forceReload} // Re-render map when this change
> 				style={styles.map}
> 				initialRegion={{
> 					latitude: note.location.coords.latitude,
> 					longitude: note.location.coords.longitude,
> 					latitudeDelta: 0.01,
> 					longitudeDelta: 0.01,
> 				}}
> 				onMapReady={() => {
> 					setMapReady(true);
> 					console.log('Map loaded');
> 				}}
> 			>
> 				<Marker
> 					coordinate={{ latitude: note.location.coords.latitude, longitude: note.location.coords.longitude }}
> 					title={note.title}
> 					description={note.note}
> 				></Marker>
> 			</MapView>
> 		</View>
> 	);
> };
> 
> 
> const styles = StyleSheet.create({
> 	map: {
> 		width: 300,
> 		height: 200,
> 	},
> 	modalView: {
> 		margin: 20,
> 		backgroundColor: 'white',
> 		borderRadius: 20,
> 		padding: 35,
> 		alignItems: 'center',
> 		shadowColor: '#000',
> 		shadowOffset: {
> 			width: 0,
> 			height: 2,
> 		},
> 		shadowOpacity: 0.25,
> 		shadowRadius: 4,
> 		elevation: 5,
> 	},
> });
> ```

This is good, but i was still having the issue of it not working sometimes on android, so update on this is
```
useEffect(() => {
    const timer = setTimeout(() => {
      if (!mapReady) {
        console.warn("Map was not ready within 2 second. Forcing re-render.");
        setForceReload((prev) => prev + 1);
      }
    }, 2000);

    return () => clearTimeout(timer);
  }, [mapReady, forceReload]);
```

**Comment by edgarscr** [comment]
> I'm facing this problem and I came up with a somewhat inelegant workaround. I've noticed that the MapView component doesn't actually invoke the onMapReady callback when the markers are not loaded. So, using a state variable and `useEffect`, I check if the markers are not loaded and force the re-render of the map if that's the case. You can take a look at this code for some more insight, hopefully it's not too ugly
> 
> import { useEffect, useState } from 'react';
> import { StyleSheet, View } from 'react-native';
> 
> import MapView, { Marker } from 'react-native-maps';
> 
> export const NoteItem = ({ note }) => {
> 	const [mapReady, setMapReady] = useState(false);
> 	const [forceReload, setForceReload] = useState(0);
> 
> 	useEffect(() => {
> 		const timer = setTimeout(() => {
> 			if (!mapReady) {
> 				console.warn('Map was not ready within 1 second. Forcing re-render.');
> 				setForceReload((prev) => prev + 1);
> 			}
> 		}, 1000);
> 
> 		return () => clearTimeout(timer);
> 	}, [mapReady]);
> 
> 	return (
> 		<View>
> 			<MapView
> 				key={forceReload} // Re-render map when this change
> 				style={styles.map}
> 				initialRegion={{
> 					latitude: note.location.coords.latitude,
> 					longitude: note.location.coords.longitude,
> 					latitudeDelta: 0.01,
> 					longitudeDelta: 0.01,
> 				}}
> 				onMapReady={() => {
> 					setMapReady(true);
> 					console.log('Map loaded');
> 				}}
> 			>
> 				<Marker
> 					coordinate={{ latitude: note.location.coords.latitude, longitude: note.location.coords.longitude }}
> 					title={note.title}
> 					description={note.note}
> 				></Marker>
> 			</MapView>
> 		</View>
> 	);
> };
> 
> 
> const styles = StyleSheet.create({
> 	map: {
> 		width: 300,
> 		height: 200,
> 	},
> 	modalView: {
> 		margin: 20,
> 		backgroundColor: 'white',
> 		borderRadius: 20,
> 		padding: 35,
> 		alignItems: 'center',
> 		shadowColor: '#000',
> 		shadowOffset: {
> 			width: 0,
> 			height: 2,
> 		},
> 		shadowOpacity: 0.25,
> 		shadowRadius: 4,
> 		elevation: 5,
> 	},
> });

forcing isReady to true makes the map load, but you can't move it, you can't zoom, you can't do anything. the new architecture breaks some markers, i disable it and the markers come out fine. but i still have the problem that i can't move the map. unless i send a direct command by code. but in a tactile way it doesn't work. it can only be seen.

**Comment by rahul-bmninfotech** [comment]
Still facing same issue nothing works

**Comment by shwanton** [comment]
Try using [RN v0.76.7](https://www.npmjs.com/package/react-native/v/0.76.7) w/ new arch enabled to fix the Android issue where the map won't use the initial region on subsequent renders.

https://github.com/facebook/react-native/pull/48823 was added to the fix Interop events that fire before the mounting manager is ready (events like `onMapReady`). This change was picked to [v0.76.7](https://github.com/facebook/react-native/releases/tag/v0.76.7)

**Comment by kayyappa-facilgo** [comment]
I am using like this 
<MapView
              testID="task_assignment_map"
              accessibilityLabel="task_assignment_map"
              provider={
                 PROVIDER_DEFAULT
              }
              style={styles.map}
              onMapReady={() =>
                setConfig(setting => ({...setting, mapLoading: false}))
              }
              zoomControlEnabled={true}
              initialRegion={{
                latitude: config.events[0]?.coordinates.latitude
                  ? config.events[0].coordinates.latitude
                  : 37.0902,
                longitude: config.events[0]?.coordinates.longitude
                  ? config.events[0].coordinates.longitude
                  : -95.7129,
                latitudeDelta: 1,
                longitudeDelta: 1,
              }}
              collapsable={true}
              mapType="standard">
              {renderMarkers(
                config.tasks,
                config.events,
                handleTaskPress,
                navigation,
              )}
            </MapView>

const renderMarkers = (
  tasks: Task[],
  events: MappedEvent[],
  handleTaskPress: (event: MappedEvent, from: 'CALENDAR' | 'MAP') => void,
  navigation: any,
) => {
  if (_.isEmpty(events)) {
    return null;
  }

  return events.map((marker, index) => {
    const task = tasks.find((task: Task) => task.id === marker.id);

    if (!task) {
      return null;
    }

    return (
      <Marker
        key={`task_assignment_map_marker_${index}`}
        coordinate={marker.coordinates}
        onPress={() =>
          marker.mappedEvents.length > 1
            ? handleTaskPress(marker, 'MAP')
            : navigation.navigate('InspectionDetail', {id: marker?.id})
        }>
        <MarkerIcon color={marker.markerColor} number={marker.markerOrder} />
      </Marker>
    );
  });
};
the marker icon is not coming in android whereas it is working fine in iOS.Can anyone help me

**Comment by akakiplimo** [comment]
Using the beta version helped me sort out this issue. I was experiencing this issue with the latest [1.26.11](https://www.npmjs.com/package/react-native-maps/v/1.26.11)  and alpha [1.25.0-alpha.8](https://www.npmjs.com/package/react-native-maps/v/1.25.0-alpha.8) versions

This is my current setup

```
"react": "19.0.0",
"react-native": "0.78.0",
"react-native-maps": "^2.0.0-beta.15",
```
