### ISSUE TITLE
Android runtime error - ‘RNMapsAirModule’ Could Not Be Found”- on react native 0.79

### ISSUE THREAD

**Issue by fobos531** [react-native-maps/react-native-maps#5424]
### Summary

@salah-ghanim 

It seems something changed in the codegen config for RN 0.79 or RN 0.78, as I'm getting 

Invariant Violation: TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” Error in React Native

upon launch. This works perfectly fine on RN 0.77. Not sure what the issue is exactly

### Reproducible sample code

```TSX
Available here: https://github.com/fobos531/react-native-maps-repro
```

### Steps to reproduce

Add your google maps api key to the android manifest, compile and run the app, and use `npx expo start` to connect the development client. 

### Expected result

The android map should be initialized correctly.

### Actual result

Getting Invariant Violation: TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” Error in React Native

### React Native Maps Version

1.22.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.79.0

### What version of Expo are you using?

SDK 53

### Device(s)

Android emulator

**Comment by fobos531** [comment]
Perhaps this is the issue? https://github.com/facebook/react-native/commit/825492b1999b62de708e6f40d5d5de8d3d7cb8a9#diff-6a85605fb6d3af7508855ba2db087f115058d7fe15e0ee6670f2dfce84671fff

Maybe the codegen is now much more strict about which parameter types are allowed - only primitives are, and react-native-maps uses objects as well (Region etc.) - maybe that needs to be changed?

**Comment by NishS2211** [comment]
Getting the same issue, try downgrading the version to 1.18.0 for the time being till they fix this issue in 1.22.1. It worked all fine for me on react native 0.78.0.

**Comment by Rohit3523** [comment]
Any update?

**Comment by Killian-Aidalinfo** [comment]
Any update ? I've same issue on macos with "react-native": "0.76.9",

**Comment by aditikiri** [comment]
@NishS2211 hack worked for me on React Native 0.79.1

**Comment by Rohit3523** [comment]
I am able to use the library without any package in React Native 0.79.1 but it break as soon as I add Expo 53-beta sdk

**Comment by fobos531** [comment]
> Hello, if I delete “react-native-maps” in app.json in the plugin part, it works without error. I have a working map.
> 
> I do not know the repercussions of this action (I am a beginner in react & react native).
> 
> repo example : [Killian-Aidalinfo/mapApp](https://github.com/Killian-Aidalinfo/mapApp?rgh-link-date=2025-04-24T09%3A43%3A11.000Z)

@Killian-Aidalinfo  - you're using an old version of react-native-maps which is not officially new arch compatible

**Comment by Killian-Aidalinfo** [comment]
Hi @fobos531, thanks for your reply, if I use the latest version of react-native-maps I get this warning:

The following packages need to be updated for better compatibility with the installed expo version:
  react-native-maps@1.22.6 - expected version: 1.18.0
Your project may not work properly until you install the expected package versions.


My package.json : 

```json
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@vgatica9/react-native-leaflet-maps": "^0.2.3",
    "expo": "~52.0.46",
    "expo-blur": "~14.0.3",
    "expo-constants": "~17.0.8",
    "expo-font": "~13.0.4",
    "expo-haptics": "~14.0.1",
    "expo-linking": "~7.0.5",
    "expo-location": "^18.0.10",
    "expo-router": "~4.0.20",
    "expo-splash-screen": "~0.29.24",
    "expo-status-bar": "~2.0.1",
    "expo-symbols": "~0.2.2",
    "expo-system-ui": "~4.0.9",
    "expo-web-browser": "~14.0.2",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.9",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-leaflet-view": "^1.0.3",
    "react-native-maps": "^1.22.6",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.6",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
```

I created the project yesterday with this command: 

```bash
npx create-expo-app@latest
```

**Comment by 42nao** [comment]
same issue with react native 0.76.9 and expo 52

**Comment by art9mid** [comment]
Same issue with react native 0.79.1 and Expo 53

**Comment by iliyas-kiwimesh** [comment]
Same issue with 

```
{
  "name": "********",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "format": "prettier --write ."
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.1.0",
    "@react-native-async-storage/async-storage": "^2.1.2",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "expo": "~52.0.46",
    "expo-blur": "~14.0.3",
    "expo-constants": "~17.0.8",
    "expo-font": "~13.0.4",
    "expo-haptics": "~14.0.1",
    "expo-linking": "~7.0.5",
    "expo-location": "^18.0.10",
    "expo-router": "~4.0.20",
    "expo-splash-screen": "~0.29.24",
    "expo-status-bar": "~2.0.1",
    "expo-symbols": "~0.2.2",
    "expo-system-ui": "~4.0.9",
    "expo-web-browser": "~14.0.2",
    "prettier": "^3.5.3",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.9",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-get-random-values": "^1.11.0",
    "react-native-google-places-autocomplete": "^2.5.7",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "^1.22.6",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-swiper": "^1.6.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5",
    "zustand": "^5.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.6",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}
```

**Comment by VoldemarVova** [comment]
Same issue with

{
  "name": "************",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --clear",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "codegen": "graphql-codegen",
    "codegen-watch": "graphql-codegen -w",
    "eas-build-prod": "eas build --profile production",
    "eas-build-prev": "eas build --profile preview",
    "eas-submit-ios-latest": "eas submit -p ios --latest",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,css,md}\"",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@apollo/client": "^3.13.5",
    "@expo/react-native-action-sheet": "^4.1.1",
    "@expo/vector-icons": "^14.0.4",
    "@gorhom/bottom-sheet": "^5.1.2",
    "@react-native-async-storage/async-storage": "^2.1.2",
    "@react-native-community/datetimepicker": "8.2.0",
    "@react-native-community/hooks": "^3.0.0",
    "@react-navigation/bottom-tabs": "^7.3.3",
    "@react-navigation/native": "^7.0.19",
    "@reduxjs/toolkit": "^2.6.1",
    "@sentry/react-native": "^6.10.0",
    "@shopify/flash-list": "^1.8.0",
    "date-fns": "^4.1.0",
    "expo": "^52.0.46",
    "expo-blur": "~14.0.3",
    "expo-constants": "~17.0.8",
    "expo-dev-client": "^5.0.15",
    "expo-font": "~13.0.4",
    "expo-haptics": "~14.0.1",
    "expo-image": "^2.0.7",
    "expo-image-picker": "^16.0.6",
    "expo-linear-gradient": "^14.0.2",
    "expo-linking": "~7.0.5",
    "expo-localization": "^16.0.1",
    "expo-location": "^18.0.8",
    "expo-navigation-bar": "^4.0.8",
    "expo-router": "~4.0.20",
    "expo-secure-store": "^14.0.1",
    "expo-splash-screen": "~0.29.22",
    "expo-standard-web-crypto": "^2.0.1",
    "expo-status-bar": "~2.0.1",
    "expo-symbols": "~0.2.2",
    "expo-system-ui": "~4.0.8",
    "expo-updates": "^0.27.4",
    "expo-web-browser": "~14.0.2",
    "geolib": "^3.3.4",
    "i18next": "^24.2.3",
    "i18next-intervalplural-postprocessor": "^3.0.0",
    "js-base64": "^3.7.7",
    "jwt-decode": "^4.0.0",
    "libphonenumber-js": "^1.12.6",
    "lodash": "^4.17.21",
    "luxon": "^3.6.0",
    "phone": "^3.1.58",
    "re-reselect": "^5.1.0",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-i18next": "^15.4.1",
    "react-native": "0.76.9",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-maps": "^1.20.1",
    "react-native-mask-input": "^1.2.3",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-paper": "^5.13.5",
    "react-native-reanimated": "~3.16.7",
    "react-native-safe-area-context": "5.3.0",
    "react-native-screens": "~4.9.2",
    "react-native-svg": "^15.11.2",
    "react-native-toast-message": "^2.2.1",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.13.5",
    "react-redux": "^9.2.0",
    "redux-saga": "^1.3.0",
    "uuid": "^11.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.26.10",
    "@eslint/js": "^9.23.0",
    "@graphql-codegen/cli": "^5.0.5",
    "@types/jest": "^29.5.14",
    "@types/lodash": "^4.17.16",
    "@types/luxon": "^3.4.2",
    "@types/react": "~18.3.20",
    "@types/react-native": "^0.73.0",
    "@types/react-test-renderer": "^18.3.1",
    "@types/supercluster": "^7.1.3",
    "@typescript-eslint/eslint-plugin": "^8.28.0",
    "@typescript-eslint/parser": "^8.28.0",
    "eslint": "^9.23.0",
    "eslint-config-prettier": "^10.1.1",
    "eslint-plugin-prettier": "^5.2.5",
    "eslint-plugin-react": "^7.37.4",
    "globals": "^16.0.0",
    "jest": "^29.7.0",
    "jest-expo": "~52.0.6",
    "prettier": "3.5.3",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.8.2",
    "typescript-eslint": "^8.28.0"
  },
  "private": true
}

**Comment by salah-ghanim** [comment]
this could be due to the fact that we're shipping the generated code as part of the lib itself, which is not often used by react-native libs. 

I will try to update the lib to support latest react-native and run codegen again, this might solve the issue, but then we're again having to use a fixed version of the lib with fixed react-native version which I dislike.

**Comment by fobos531** [comment]
> this could be due to the fact that we're shipping the generated code as part of the lib itself, which is not often used by react-native libs. 
> 
> I will try to update the lib to support latest react-native and run codegen again, this might solve the issue, but then we're again having to use a fixed version of the lib with fixed react-native version which I dislike.
> 
> 

@salah-ghanim Is there a reason why the generated code needs to be shipped with the library instead of letting codegen run on app build?

**Comment by trevor-coleman** [comment]
Trying this with:
```
  "react-native-maps": "1.23.4"*
  "expo": "^53.0.0",
  "react": "19.0.0",
  "react-native": "^0.79.2",
```

using this in my config:

```
{ "plugins": [
    [
        "react-native-maps",
        {
          androidGoogleMapsApiKey: "...",
          iOSGoogleMapsApiKey: "...",
        },
   ]]}
```

and getting these errors::

**Android**
```
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
```

**Comment by salah-ghanim** [comment]
fixed in [1.23.6](https://github.com/react-native-maps/react-native-maps/compare/v1.23.5...v1.23.6) please submit again if it doesn't work.

@fobos531 it has nothing to do with checked in code

**Comment by VoldemarVova** [comment]
> Same issue with

Same issue with
"react-native-maps": "^1.23.7",

**Comment by avglrd** [comment]
same issue on react-native@0.79.2 and react-native-maps@1.23.7 android

**Comment by tschoffelen** [comment]
Works for me, thanks for the quick fix!

**Comment by avglrd** [comment]
@tschoffelen which versions are you using?

**Comment by tschoffelen** [comment]
@tim-baecker I'm not using ingest, just plain RN `0.79.2` and RN-maps `1.23.7`

**Comment by Unaidedsteak** [comment]
Also having the same issue, but using expo on a fresh project:

```
"react-native": "0.79.2",
"react-native-maps": "^1.23.7",
```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found. Verify that a module by this name is 
registered in the native binary., js engine: hermes

```

**Comment by serginogal** [comment]
I'm also having the `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes` error.

```
"expo": "^53.0.8",
"react-native": "0.79.2",
"react-native-maps": "1.23.7",
```

I've checked other `react-native-maps` versions but it seems that the error started appearing from version `1.21.0` .
With `1.20.1` the error did not appear.

**Comment by Pribal** [comment]
> Verified `react-native-maps@~1.23.7` works for me on `expo@53.0.7`, `react-native@0.79.2`, and new architecture is enabled for Android.

I use the same version and i always get the same error. Did you do something to make it work or out of the box ?

**Comment by VoldemarVova** [comment]
updated to
    "expo": "^53.0.9",
    "react-native": "0.79.2",
    "react-native-maps": "1.23.7",

the problem persists

**Comment by Luke-Doo** [comment]
I have the same error, please let me know if anyone has fixed it😥

**Comment by Misyuk-T** [comment]
+ have the same issue with expo

**Comment by MarkMurphy94** [comment]
Seem to be having the same problem on:

`"react-native-maps": "^1.23.8",`
`"expo": "~53.0.8"`
`"react-native": "0.79.2"`

**Comment by Cha0yue** [comment]
I did not see this problem when using react-native-maps version 1.20.1 or 1.23.8

```
"expo": "~53.0.9",
"react-native": "0.79.2",
"react-native-maps": "1.20.1" / "react-native-maps": "1.23.8"
```

Built the apk locally (with `npx expo run:android`) and using eas and both were fine.

**Comment by HADO564** [comment]
Seems that despite this issue being closed, the problem everyone is facing is still there. If anyone has a potential fix, pls dont hesitate to share.

**Comment by Yassdrk** [comment]
Hello,
It's still not working. I don't understand why this issue is closed.

I just tried npx expo install react-native-maps as recommended, it's installing version     "react-native-maps": "1.20.1"

but i have this issue PluginError: Package "react-native-maps" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token '<'

**Comment by Cha0yue** [comment]
Yeah react-native-maps v1.20.1 does not have a valid config plugin. It's mentioned [here](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#expo) that only v1.22 and above has the plugin.

For v1.20.1 you can refer to the [expo docs](https://docs.expo.dev/versions/latest/sdk/map-view/#add-the-api-key-to-your-project) for the configuration

**Comment by matija92** [comment]
I'm having the same issue using the latest packages. Can anyone share a combination of versions that works on Android?

**Comment by elisjoaquim** [comment]
Hello,

I'm using Expo 53, updated to version 1.24.3, and it appears the issue has been resolved.

"dependencies": {
    "expo": "~53.0.9",
    "react-native-maps": "^1.24.3"
  }

**Comment by matija92** [comment]
Not working for me unfortunately

**Comment by elisjoaquim** [comment]
> Not working for me unfortunately

@matija92 ooh, that's not good.
Tell me one thing, did you added this config to your app.json?

{
  "expo": {
    "plugins": [
      [
        "react-native-maps",
        {
          "iosGoogleMapsApiKey": "YOUR_KEY_HERE",
          "androidGoogleMapsApiKey": "YOUR_KEY_HERE"
        }
      ]
    ]
  }
}

If not, please add it. Another thing I noticed is that running new arch with Expo Go, does not blend well.
My suggestion is for you to run `npx expo prebuild` and use expo dev-client. Let me know if works.

By the way, if you're not aware of this, just know that iosGoogleMapsApiKey is not mandatory, you can omit it.

**Comment by nmauffre** [comment]
Same issue there with :

"react-native": "^0.79.0",
"react-native-maps": "1.24.3",
 "expo": "53.0.11"

But when i do the build : eas build --platform android and eas submit --platform android. I don't have the error at launch. 
In expo go, it crash at launch.

**Comment by iliyas-kiwimesh** [comment]
why is this closed? we are facing same issue. @fobos531

**Comment by matija92** [comment]
@elisjoaquim  I managed to resolve the issue on Android with the following versions:

"expo": "53.0.11"
"react": "19.0.0"
"react-native": "0.79.3"
"react-native-maps": "1.20.1"

I realized that my map was hidden and had to update my css with a fixed width property. Thanks for the help!

**Comment by enzodamascena** [comment]
I'm just using react-native 0.79.3 without expo and I got the same error testing react-native-maps in 1.24.3, 1.23.7, 1.20.1, 1.21.0

**Comment by VoldemarVova** [comment]
These problems started after "react-native-maps": "1.20.1".

**Comment by mMarcos208** [comment]
same issue on android with fabric enabled. Ios works well.

```
react-native 0.79.3 
react-native-maps 1.24.3
```

**Comment by stanleyyeung** [comment]
> [@elisjoaquim](https://github.com/elisjoaquim) I managed to resolve the issue on Android with the following versions:
> 
> "expo": "53.0.11" "react": "19.0.0" "react-native": "0.79.3" "react-native-maps": "1.20.1"
> 
> I realized that my map was hidden and had to update my css with a fixed width property. Thanks for the help!

Thanks! These versions worked for me but I also had to downgrade the architecture to the previous one by adding "newArchEnabled": false to app.json.

**Comment by AASHIK-2512** [comment]
i got the same issue its related to how you install i think , i am using expo and i installed using 
`react native maps`.

but when i uninstalled react-native-maps and then installed it with expo 
`npx expo install react-native-maps` 
issue is fixed even the new arch is enabled.

**Comment by apertureless** [comment]
I have the same issue.

```❯ npx expo install react-native-maps
› Installing 1 SDK 53.0.0 compatible native module using yarn
> yarn add react-native-maps@1.20.1
```

Results in:

```
Skipping config plugin check: Package "react-native-maps" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token '<'
```

I have 

```
  "expo": "^53.0.19",
    "react": "19.0.0",
    "react-native": "0.79.5",
```

**Comment by JustKaylaThings** [comment]
Following this documentation from Expo worked for me: [Expo Maps Documentation][https://docs.expo.dev/versions/latest/sdk/map-view/]

**BEFORE**

    "expo": "~53.0.17",
         "react-native-maps": "1.24.3"

In app.json ---
"expo":{
 "plugins": [
        "react-native-maps",
        {
          "iosGoogleMapsApiKey": "{YOUR_GOOGLE_API_KEY}",
          "androidGoogleMapsApiKey": "{YOUR_GOOGLE_API_KEY}"
        }

------

**AFTER**
Instead of putting the api keys in the plugin section, I put the api keys in each of the platform config fields. And yes, I also understand that 1.22 or higher is required to add the plugins, but even upgrading to that version did not work for me. 


   "android": {
      "config": {
        "googleMaps": {
          "apiKey": "{YOUR_GOOGLE_API_KEY}"
        }
      }
    },

Dependencies:

    "expo": "~53.0.17",
          "react-native-maps": "1.20.1"

**Comment by tabask0** [comment]
still happening on 

    "expo": "~53.0.20",
    "react-native-maps": "^1.24.10"

**Comment by wgnsimon** [comment]
still happening
    "expo": "53.0.20",
    "react-native": "0.79.5",

the solution with downgrading to 1.20.1 is working for me, but I think it's really crap in the long run if it only works with an old function and new bug fixes etc. can't be applied..

**Comment by ol4juwon** [comment]
1.24.3 works for me in dev build. expo go build didn't work

**Comment by neillindberg** [comment]
Why is this closed? It is totally true as of today. We found after upgrade to minor version 25, during a Native upgrade, broke things and rolling back to 1.4.0 makes things work again, but as others have pointed out we'd of course rather have the newest features and bug fixes.

**Comment by geiz** [comment]
@neillindberg 

I'm ran into this issue for iOS on Bare RN.

Solved by following the `/example` in this repo & started cleaning some unneeded packages

I was using 
`react-native: @0.81.4`
`react-native-maps: @1.26.6`
`node 24.8.0`
`npm 11.6.0`

1. Removed `react-native-reanimated` and switched to `react-native-worklets`

2. Added new arch to Podfile
```target 'crmMobileApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => true,
  )
...
```
3. new arch to Plist
<key>RCTNewArchEnabled</key>
	<true/>

4. Fully clean & reinstall pods / build.
`bundle exec pod install` 

And... it worked.

react-native-renanimated, even if not used but exist in node_modules will give random package issues.

GL :)

**Comment by geiz** [comment]
I ran into this issue for iOS on Bare RN.

Solved by following the /example in this repo & started cleaning some unneeded packages

I was using
`react-native: @0.81.4`
`react-native-maps: @1.26.6`
`node 24.8.0`
`npm 11.6.0`

1. Removed `react-native-reanimated` and switched to `react-native-worklets: ^0.5.1`

2. Added new arch to Podfile

```
config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => true,
  )
...
```

3. Added new arch to Plist
`<key>RCTNewArchEnabled</key>
	<true/>`

4. Fully clean & reinstall pods / build.
`bundle exec pod install`

And... it worked.

react-native-renanimated, even if not used but exist in node_modules will give random package issues.

GL :)

**Comment by theerej-s** [comment]
In my setup, I was using expo-modules, and we had a plugin to inject the API key for `react-native-maps` into the `AndroidManifest.xml` file via `app.config.ts.`

The module name in my configuration was exactly `react-native-maps`, and we had a corresponding `app.plugin.js`. However, it appeared that the `react-native-maps` library was being skipped during compilation because the module with the same name was already being compiled through the `app.config.ts` configuration.

✅ Fix (Old Architecture)

To resolve this, I renamed the folder from `react-native-maps` to `react-native-maps-config`, then ran a pre-build. After that, the `react-native-maps` module compiled correctly, including all its required components such as `RNMapsAirModule`.

🧩 Versions Used
```
"expo": "54.0.12",
"react-native": "0.81.4",
"react-native-maps": "1.20.1"
```

**Comment by kelyaenn** [comment]
Does anyone have the issue in testing using jest ?

No issues on the devices but when running jest for tests I have same error : Invariant Violation: TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” Error in React Native

RN 0.82.1 and react-native-maps 1.26.1 without expo

**Comment by logesh2496** [comment]
> Does anyone have the issue in testing using jest ?
> 
> No issues on the devices but when running jest for tests I have same error : Invariant Violation: TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” Error in React Native
> 
> RN 0.82.1 and react-native-maps 1.26.1 without expo


I face the same above issue on "react-native-maps": "^1.26.17" & "react-native": "0.80.1". 

any fix? thanks

**Comment by Thiernod98** [comment]
I've spent several days trynna figure out the issue with MapView using expo ~54.0.24; react-native 0.81.5; react-native-maps 1.20.1.  First of all if you're using expo, you need to do npx expo install react-native-maps, and add a View with style flex:1 and same for MapView like in the codes below!

import MapView, {DEFAULT_PROVIDER} from "react-native-maps";
import { View } from "react-native";
    

const Map = ()=>{
    
    return (
        <View style={{ flex: 1 }}>
          <MapView style={{ flex: 1 }}  provider={DEFAULT_PROVIDER}/>
        </View>
    )
}
export default Map;

**Comment by fortune-cook1e** [comment]
> Following this documentation from Expo worked for me: [Expo Maps Documentation][https://docs.expo.dev/versions/latest/sdk/map-view/]
> 
> **BEFORE**
> 
> ```
> "expo": "~53.0.17",
>      "react-native-maps": "1.24.3"
> ```
> 
> In app.json --- "expo":{ "plugins": [ "react-native-maps", { "iosGoogleMapsApiKey": "{YOUR_GOOGLE_API_KEY}", "androidGoogleMapsApiKey": "{YOUR_GOOGLE_API_KEY}" }
> 
> **AFTER** Instead of putting the api keys in the plugin section, I put the api keys in each of the platform config fields. And yes, I also understand that 1.22 or higher is required to add the plugins, but even upgrading to that version did not work for me.
> 
> "android": { "config": { "googleMaps": { "apiKey": "{YOUR_GOOGLE_API_KEY}" } } },
> 
> Dependencies:
> 
> ```
> "expo": "~53.0.17",
>       "react-native-maps": "1.20.1"
> ```

Thank you!!! It really works for me

**Comment by jkcarraher** [comment]
I'd like to confirm this is still an issue with react-native-maps `1.27.1`. Updating plugins the way described in documentation does not fix the issue. 

I'm unable to get the package to bundle on android using any version newer than `1.20.1`.
