### ISSUE TITLE
Android: Custom markers don't display fully

### ISSUE THREAD

**Issue by stjasink** [react-native-maps/react-native-maps#5728]
### Summary

I have some markers that use Views and CSS to display a custom marker as an outline containing a number, with a pin below. On iOS these display as intended. On Android, only the outline displays and the number text and pin are missing.

This worked fine in version 1.20.1 before I upgraded to 1.26.1

I have seen a few issues raised about Android markers on here, but not specifically like this. So this might be a symptom of a more general issue with Android markers.

On IOS, displays as intended:

<img width="241" height="312" alt="Image" src="https://github.com/user-attachments/assets/c358601d-c635-4093-91f8-5130e99d6ed2" />

On Android, only partially displayed:

<img width="281" height="346" alt="Image" src="https://github.com/user-attachments/assets/8fe0884b-2cf1-43b6-9ef0-46c31f0a9c2e" />

### Reproducible sample code

```TSX
import MapView, { Marker } from 'react-native-maps';
import { StyleSheet, Text, View } from 'react-native';

function App() {

  return (
    <View style={styles.container}>
      <MapView
        provider="google"
        style={styles.map}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      >
        <Marker
          coordinate={{latitude: 37.79, longitude: -122.45}}
          tracksViewChanges={false}>
          <View style={styles.markerContainer}>
            <View style={styles.markerTop}>
              <Text style={styles.markerText}>5</Text>
            </View>
            <View style={styles.markerPin} />
          </View>
        </Marker>
      </MapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  markerContainer: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  markerTop: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 5,
    borderWidth: 3,
    borderColor: 'green',
  },
  markerPin: {
    width: 3,
    height: 5,
    backgroundColor: 'green',
  },
  markerText: {
    fontWeight: 'bold',
    color: 'black',
  },
});

export default App;
```

### Steps to reproduce

Create a new project with react native 0.81.1
Install react-native-maps 1.26.1
Paste the code above into App.tsx
Run on iOS to see the marker display fully
Run on Android to see the marker only partially displayed

### Expected result

The marker displays fully on both iOS and Android

### Actual result

The marker displays fully on iOS but only displays partially on Android

### React Native Maps Version

1.26.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.81.1

### What version of Expo are you using?

Not using Expo

### Device(s)

Android emulator

**Comment by alejandrochavezc** [comment]
I’m experiencing the same issue with the same configuration described above (React Native 0.81.1 + react-native-maps 1.26.1, without Expo) on Android. I haven’t tested on iOS. Downgrading to version 1.20.1 solved the problem.

**Comment by mMarcos208** [comment]
Downgrading to version 1.20.1 works, but display cut marker.

**Comment by iuliazaharie** [comment]
bumped into a similar problem - downgrading to 1.20.1 from 1.26.1 worked in my case as well for an app using react native 0.79.2

**Comment by andkom** [comment]
same

**Comment by LukasB-DEV** [comment]
have the same issue. Works if i remove the view as child. @salah-ghanim can you please check this?

**Comment by mMarcos208** [comment]
Custom marker not display when using image as children.

"react-native-maps": "^1.26.6"

```
    <Marker
      draggable
      tracksViewChanges={tracksViewChanges}
      stopPropagation
      onLayout={() => {
        trackViewChangesTimeout.current = setTimeout(() => {
          setTracksViewChanges(false)
        }, 500)
      }}
      {...props}
    >
       <Image
           source={reference.id === 1 ? pontoCochoImage : creepfeedingImage}
           style={managementStyles.markerImage}
           resizeMode="contain"/>
    </Marker>
```

**Comment by ChromeQ** [comment]
> Custom marker not display when using image as children

This looks to be a separate issue @mMarcos208, which has been raised:
https://github.com/react-native-maps/react-native-maps/issues/5707

Let's try to keep this one specific to the OP.

**Comment by ChromeQ** [comment]
After literally days of trial and error, build woes, headaches, heartbreaks, false hopes, hassle and eventual acceptance, I can finally give my full and honest review and solution over here:
https://github.com/react-native-maps/react-native-maps/issues/5739#issuecomment-3316034503

**Comment by ynejati** [comment]
Issue still present in version 1.26.14, in case anyone is wondering.  Easy to replicate.

**Comment by AlejandroRM-DEV** [comment]
+1 with 1.26.14

**Comment by DhruvKalpeshThakar** [comment]
Could you Let us know How to resolve the issue with 1.26.14 Version ? @ChromeQ

**Comment by ChromeQ** [comment]
If you read my comment linked above @DhruvKalpeshThakar  then I don't think there is a way to have a stable and bug free app with the newer versions of react-native-maps, the only way I've managed to get it to work well is with v1.20.1 with the patch (mentioned in the comment link) to fix android clipped custom icons.

Hopefully when more of the open issues are resolved and some serious testing is implemented in the project then I can consider upgrading to later new architecture enabled versions.

**Comment by DhruvKalpeshThakar** [comment]
> If you read my comment linked above [@DhruvKalpeshThakar](https://github.com/DhruvKalpeshThakar) then I don't think there is a way to have a stable and bug free app with the newer versions of react-native-maps, the only way I've managed to get it to work well is with v1.20.1 with the patch (mentioned in the comment link) to fix android clipped custom icons.
> 
> Hopefully when more of the open issues are resolved and some serious testing is implemented in the project then I can consider upgrading to later new architecture enabled versions.

Thanks your patch 1.26.6 worked!

**Comment by ChromeQ** [comment]
My patch is only for v1.20.1. It won't apply to 1.26.6 and the thing it fixed was android clipped icons which are already fixed somewhere between 1.20.1 and 1.26.6 so you can remove the patch, it's not doing anything for you.

**Comment by DhruvKalpeshThakar** [comment]
> My patch is only for v1.20.1. It won't apply to 1.26.6 and the thing it fixed was android clipped icons which are already fixed somewhere between 1.20.1 and 1.26.6 so you can remove the patch, it's not doing anything for you.

Okay Don't know how Now CustomMarker were showing after using your patch , May be It could have been solved with the 1.26.6 version Itself!

**Comment by ChromeQ** [comment]
@DhruvKalpeshThakar Yes, it was fixed in [v1.23.12](https://github.com/react-native-maps/react-native-maps/blob/master/CHANGELOG.md#bug-fixes-33)

**Comment by omerts** [comment]
this issue is still hapenning in `1.26.17`

**Comment by cortigeronimo** [comment]
Same issue in 1.26.18; works only with trackViews=true, but performance suffers.

**Comment by saurori** [comment]
I'm still seeing this issue in `1.26.19`. The custom marker content (icon in my case) will show if you cause a redraw / view refresh by zooming out then in which refreshes markers.

**Comment by Lab3l** [comment]
I encountered the same issue with built versions on android devices. I'm now using the latest 1.26.19 version and removed the need for tracksViewChanges with adding a slight 250ms delay after map initialized and conditionally rendering the markers. No more flickering or missing markers

**Comment by Usman4358** [comment]
The issue is with new architecture not with the react native map version. I disabled new architecture and the issue resolved. But I need a solution for this because i am using Flashlist and it's not compatible with old architecture.

**Comment by quuentinho** [comment]
Did you have any updates on this issue ?

**Comment by vladanmikic** [comment]
Also happening on `1.24.13` and `1.26.0` with React Native `0.79.6`. Toggling `tracksViewChanges` fixes the issue, but isn't a proper solution since it hurts performance. It worked perfectly on old architecture.

**Comment by axodevjs** [comment]
same problem

**Comment by mellertson** [comment]
Upgrading to `react-native-maps@^1.23.12` worked for me on Android.  The `<Marker><View>custom stuff</View></Marker>` now displays `custom stuff` without clipping.  I am able to resize by using `style={{width:100,height:100}}` on the view inside `<Marker>`.  

Thanks so much, you're a life saver!!!

**Comment by karimcambridge** [comment]
`"react-native-maps": "1.27.2"` happening on this version

```
<Marker
			key={group.key}
			coordinate={{
				latitude: group.latitude,
				longitude: group.longitude,
			}}
			anchor={{ x: 0.5, y: 1 }}
			title={group.events.length > 1 ? `${group.venue} (${group.events.length})` : group.events[0].name}
			onPress={() => onVenuePress(group)}
			tracksViewChanges={true}
		>
			<Image source={EventMarkerImg} style={styles.marker} resizeMode='contain' />
		</Marker>
```

**Comment by cortigeronimo** [comment]
Any update? This issue has several months...

**Comment by stjasink** [comment]
Still relevant

**Comment by thetminko** [comment]
Confirming this on Android, with a measurement that might help pin down the mechanism.

**Environment:** React Native 0.86.0 (Expo SDK 57), New Architecture / Fabric, `PROVIDER_GOOGLE`, `react-native-maps` 1.27.2 **and** 1.29.0.

Our marker is a pill containing text, a thin connector, and a dot below it (`anchor={{ x: 0.5, y: 1 }}`). With `tracksViewChanges={false}` it renders as the pill alone — the connector and dot are missing, matching the report.

The useful part is that the React Native side lays out correctly; only the captured bitmap is short. Measuring the marker's native frame via `uiautomator`:

- broken: **77px** tall
- correct: **135px** tall

with the same bottom edge in both cases (consistent with the bottom anchor). Instrumenting `onLayout` on each child shows the RN layout was always complete and correct:

```
root      { width: 48.38, height: 51.43 }   // 51.43dp × 2.628 density = 135px
pill      { height: 29.33 }                 // 29.33dp × 2.628 = 77px  ← the captured bitmap
connector { y: 27.43, height: 8 }
dot       { y: 35.43, height: 16 }          // bottom = 51.43 ✓
```

So the snapshot is taken after the first child has laid out but before the siblings have drawn, and the bitmap is cropped to the pill. This reproduced on 5/5 cold starts.

`MapMarker.java` is **byte-for-byte identical between 1.27.2 and 1.29.0**, so this is unchanged in the latest release.

One related observation on the harder failure mode, where a marker shows the **default red pin** instead of a partial custom view. `MapMarker.requestLayout()` clears the flag whenever it runs with no children:

```java
if (getChildCount() == 0) {
    if (hasCustomMarkerView) {
        hasCustomMarkerView = false;
        clearDrawableCache();
        update(true);
    }
}
```

and `getIcon()` then returns `BitmapDescriptorFactory.defaultMarker(markerHue)`. Since `hasCustomMarkerView` is only restored in `addView()`, once that latches, re-enabling `tracksViewChanges` cannot recover it — `updateMarkerIcon()` calls `getIcon()`, which still takes the default branch. Worth being aware of when testing fixes, because it makes `tracksViewChanges` look ineffective.

**Workaround** that resolved the partial-bitmap case for us: start `tracksViewChanges` at `true` and settle it to `false` a short time after mount (and whenever the marker's visual props change), rather than pinning it `false`. 700ms is comfortable; it avoids the sustained CPU cost of leaving it on permanently while still giving the subtree time to draw. After that change the marker measured the correct 135px on 5/5 cold starts.
